services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    env_file:
      - .env
    ports:
      - '3000:3000' # Mở cổng cho NestJS

  nginx:
    build:
      context: .
      dockerfile: Docker-nginx
    container_name: nest-nginx
    depends_on:
      - nest
    environment:
      - NEST_HOST=nest
      - NEST_PORT=3000 # Đảm bảo trỏ đúng
      - NGINX_MAX_BODY=100M
    ports:
      - '8080:80' # Nginx chạy ở 80 nhưng mở port 8080 trên host
