FROM node:lts-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json yarn.lock ./
RUN yarn install --production

COPY . . 

RUN yarn build

EXPOSE 3000

CMD [ "node", "dist/main.js" ]
