services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    env_file:
      - .env.dev
    ports:
      - '3333:3000'

  nginx:
    build:
      context: .
      dockerfile: Docker-nginx
    container_name: nest-nginx
    depends_on:
      - nest
    env_file:
      - .env.dev
    ports:
      - '8080:80'
